### ISSUE TITLE
CollectiveOne

### ISSUE THREAD

**Issue by JoseOspina** [mockdeep/better#52]
Hi @mockdeep, sorry if I use this channel to get in touch with you.

We are working on a tool similar to Bettermeans. It's called CollectiveOne, and we have a prototype at [www.collectiveone.org](www.collectiveone.org). The idea now is to improve the tool by applying its method.

Would you like to get involved? We are using Spring Boot on the backend and will use Vue.js in the frontend.

Please let me know if you would be interested and we could have a chat. I live in Spain, but other contributors are in the US.

All the best,
Jose from CollectiveOne
you can get in touch with me at pepo [at] collectiveone.org

**Comment by mockdeep** [comment]
Hey @JoseOspina. Thanks for getting in touch. CollectiveOne looks like a really interesting project! Unfortunately, I'm already way over-booked in terms of projects that I'm contributing to, as evidenced by the lack of love that Better has seen. Best of luck, though, and feel free to ping me on any issues that you think I might be able to help think out.

**Comment by JoseOspina** [comment]
Yes, that makes sense indeed. I will have this in mind in case we see something. 

In fact, we are implementing the "retrospective" strategy in which every contributor of a task evaluates each other once it is finished, so maybe you could share your impression once we have a design in place. It seems like an itchy subject.

Good luck with everything on our side!
